filter:
    excluded_paths:
        - 'config/*'
        - 'docs/*'
    paths: {  }
tools:
    python_analyzer:
        enabled: true
        config:
            metrics: true
            duplication_detector:
                enabled: true
                min_mass: 25
        file_extensions:
            - .py
        filter:
            excluded_paths:
                - 'config/*'
                - 'docs/*'
