cameras:
  drive1:
    url: http://192.168.0.11/ISAPI/Streaming/channels/101/picture
    interval: 2
    store: 30
    auth: basic
    username: admin
    password: abc123
server:
  web:
    port: 8080
    listen: 0.0.0.0
