cameras:
  frontdoor:
    url: http://192.168.0.9/ISAPI/Streaming/channels/101/picture
    interval: 2
  backdoor:
    url: http://192.168.0.10/jpg/1/image.jpg
    interval: 2
server:
  web:
    port: 8080
    listen: 0.0.0.0
